### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sajshuai** [InjectiveLabs/injective-chain-releases#119]
env:
<img width="667" alt="image" src="https://github.com/InjectiveLabs/injective-chain-releases/assets/3991932/987988bb-839d-4e57-a829-9eebf6931af8">

Dec 20 02:21:56 Inj-Node systemd[1]: injectived.service: Scheduled restart job, restart counter is at 49.
Dec 20 02:21:56 Inj-Node systemd[1]: Stopped injectived.
Dec 20 02:21:56 Inj-Node systemd[1]: Started injectived.
Dec 20 02:21:56 Inj-Node bash[9274]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 20 02:21:56 Inj-Node bash[9274]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1bc8e86]
Dec 20 02:21:56 Inj-Node bash[9274]: goroutine 1 [running]:
Dec 20 02:21:56 Inj-Node bash[9274]: math/big.(*Int).Sign(...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /usr/local/go/src/math/big/int.go:39
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/cosmos/cosmos-sdk/types.Int.IsZero(...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.45.11-inj-10/types/int.go:188
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/InjectiveLabs/injective-core/injective-chain/modules/exchange/types.validateInjRewardStakedRequirementThreshold({0x28a77e0?, 0x0?})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/modules/exchange/types/params.go:512 +0x46
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x357aee0, 0xc0014941e0}, 0xc000562158, {0x3549ae8, 0xc001202cc0}, {0x3549b38, 0xc001202df0}, {0xc000575340, 0x8, 0x33}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.45.11-inj-10/x/params/types/subspace.go:245 +0x185
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/InjectiveLabs/injective-core/injective-chain/modules/exchange/keeper.(*Keeper).SetParams(_, {{0x3568fe8, 0xc000052080}, {0x357cc60, 0xc001919300}, {{0x0, 0x0}, {0xc0006e6260, 0xb}, 0x0, ...}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/modules/exchange/keeper/params.go:191 +0x1a7
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/InjectiveLabs/injective-core/injective-chain/modules/exchange/keeper.(*Keeper).InitGenesis(_, {{0x3568fe8, 0xc000052080}, {0x357cc60, 0xc001919300}, {{0x0, 0x0}, {0xc0006e6260, 0xb}, 0x0, ...}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/modules/exchange/keeper/genesis.go:14 +0x98
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/InjectiveLabs/injective-core/injective-chain/modules/exchange.AppModule.InitGenesis({{}, 0xc0011779e0, {{0x3549ae8, 0xc001202d60}, {0x3549b38, 0xc001202e10}, {0x357aee0, 0xc0014941e0}, {{0x357aee0, 0xc0014941e0}, ...}, ...}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/modules/exchange/module.go:160 +0x105
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x3568fe8, 0xc000052080}, {0x357cc60, 0xc001919300}, {{0x0, 0x0}, {0xc0006e6260, 0xb}, 0x0, ...}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.45.11-inj-10/types/module/module.go:327 +0x29d
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/InjectiveLabs/injective-core/injective-chain/app.(*InjectiveApp).InitChainer(_, {{0x3568fe8, 0xc000052080}, {0x357cc60, 0xc001919300}, {{0x0, 0x0}, {0xc0006e6260, 0xb}, 0x0, ...}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/app/app.go:907 +0x20e
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000d08540, {{0x0, 0xed86e61d0, 0x0}, {0xc0006e6260, 0xb}, 0xc0006a03a0, {0x4c0bf40, 0x0, 0x0}, ...})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.45.11-inj-10/baseapp/abci.go:63 +0x455
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001926d20, {{0x0, 0xed86e61d0, 0x0}, {0xc0006e6260, 0xb}, 0xc0006a03a0, {0x4c0bf40, 0x0, 0x0}, ...})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.34.23/abci/client/local_client.go:272 +0x118
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xa0?, {{0x0, 0xed86e61d0, 0x0}, {0xc0006e6260, 0xb}, 0xc0006a03a0, {0x4c0bf40, 0x0, 0x0}, ...})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.34.23/proxy/app_conn.go:77 +0x55
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x290b978, 0x7}}, {0xc0006e6260, 0xb}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.34.23/consensus/replay.go:319 +0xd78
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc002b3df78, {0x357db08, 0xc001488750})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.34.23/consensus/replay.go:268 +0x3c8
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x290b978, 0x7}}, {0xc0006e6260, 0xb}, 0x1, 0x0, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.34.23/node/node.go:329 +0x1b8
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/tendermint/tendermint/node.NewNode(0xc0014ee780, {0x3565950, 0xc001717a40}, 0xc000e1bbd0, {0x3543cc0, 0xc000681f98}, 0xc001912600?, 0xc0018e8480?, 0xc000e1bd30, {0x3569288, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.34.23/node/node.go:777 +0x597
Dec 20 02:21:56 Inj-Node bash[9274]: main.startInProcess(_, {{0x0, 0x0, 0x0}, {0x35861e0, 0xc001720630}, {0x0, 0x0}, {0x3570b60, 0xc0014941e0}, ...}, ...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/start.go:229 +0x693
Dec 20 02:21:56 Inj-Node bash[9274]: main.StartCmd.func2(0xc001321b00?, {0xc0016ff150?, 0x0?, 0x1?})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/start.go:131 +0x108
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/spf13/cobra.(*Command).execute(0xc001321b00, {0xc0016ff130, 0x1, 0x1})
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0012fc000)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3b4
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/spf13/cobra.(*Command).Execute(...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
Dec 20 02:21:56 Inj-Node bash[9274]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:961
Dec 20 02:21:56 Inj-Node bash[9274]: main.Execute(0xc0000021a0?)
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/root.go:118 +0x1df
Dec 20 02:21:56 Inj-Node bash[9274]: main.main()
Dec 20 02:21:56 Inj-Node bash[9274]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/main.go:9 +0x1e
Dec 20 02:21:56 Inj-Node systemd[1]: injectived.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by gorgos** [comment]
Seems like you are missing `InjRewardStakedRequirementThreshold` (`inj_reward_staked_requirement_threshold` in json) in the exchange params of the genesis file. Not sure how that would have happened, where/how did you get or generate the genesis file?

In any case, you can manually add it, current [mainnet value](https://sentry.lcd.injective.network/injective/exchange/v1beta1/exchangeParams) is `25000000000000000000`.
