### ISSUE TITLE
The mainnet config should update. genesis.json params cause panic: minimum commission rate cannot be nil: <nil>

### ISSUE THREAD

**Issue by GargantuaX** [InjectiveLabs/injective-chain-releases#120]
I want to start a mainnet.  (ref: https://docs.injective.network/nodes/RunNode/mainnet )

But injectived start failed.

I got
 ```shell
INFO[0000] initializing blockchain state from genesis.json  module=main
panic: minimum commission rate cannot be nil: <nil>
```

I tried to resolve as https://docs.cosmos.network/main/build/modules/staking#parameters

but It`s also failed.

stack:

```shell
INFO[0000] starting ABCI with Tendermint                 module=main
INFO[0000] service start                                 fields.msg="Starting multiAppConn service" impl=multiAppConn module=proxy
INFO[0000] service start                                 connection=query fields.msg="Starting localClient service" impl=localClient module=abci-client
INFO[0000] service start                                 connection=snapshot fields.msg="Starting localClient service" impl=localClient module=abci-client
INFO[0000] service start                                 connection=mempool fields.msg="Starting localClient service" impl=localClient module=abci-client
INFO[0000] service start                                 connection=consensus fields.msg="Starting localClient service" impl=localClient module=abci-client
INFO[0000] service start                                 fields.msg="Starting EventBus service" impl=EventBus module=events
INFO[0000] service start                                 fields.msg="Starting PubSub service" impl=PubSub module=pubsub
INFO[0000] service start                                 fields.msg="Starting IndexerService service" impl=IndexerService module=txindex
INFO[0000] ABCI Handshake App Info                       hash="[]" height=0 module=consensus protocol-version=0 software-version=
INFO[0000] ABCI Replay Blocks                            appHeight=0 module=consensus stateHeight=0 storeHeight=0
INFO[0000] InitChain                                     chainID=injective-1 initialHeight=1 module=main
INFO[0000] initializing blockchain state from genesis.json  module=main
panic: minimum commission rate cannot be nil: <nil>

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.InitGenesis({{0x3c4fbe0, 0xc001300e10}, {0x3c8fdc0, 0xc000a85590}, {0x3c7bc00, 0xc001060370}, {0x7f7050ee00c0, 0xc0002623c0}, {0x3c90ae0, 0xc0010e4810}, ...}, ...)
	/root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.2-inj-4/x/staking/keeper/genesis.go:31 +0x1c48
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{_, _}}, _, {_, _}, {_, _}, {_, _}}, {{0x3c755d8, ...}, ...}, ...)
	/root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.2-inj-4/x/staking/module.go:172 +0x145
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x3c755d8, 0xc00019a000}, {0x3c90990, 0xc000dd9540}, {{0x0, 0x0}, {0xc001f95c50, 0xb}, 0x0, ...}, ...}, ...)
	/root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.2-inj-4/types/module/module.go:357 +0x433
github.com/InjectiveLabs/injective-core/injective-chain/app.(*InjectiveApp).InitChainer(_, {{0x3c755d8, 0xc00019a000}, {0x3c90990, 0xc000dd9540}, {{0x0, 0x0}, {0xc001f95c50, 0xb}, 0x0, ...}, ...}, ...)
	/root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/app/app.go:983 +0x1af
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000ff6000, {{0x0, 0xed86e61d0, 0x0}, {0xc001f95c50, 0xb}, 0xc0006c6100, {0x5719e90, 0x0, 0x0}, ...})
	/root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.2-inj-4/baseapp/abci.go:78 +0x515
github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0xc000fe93e0, {{0x0, 0xed86e61d0, 0x0}, {0xc001f95c50, 0xb}, 0xc0006c6100, {0x5719e90, 0x0, 0x0}, ...})
	/root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj-1/abci/client/local_client.go:275 +0x118
github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0xc000469f08, {{0x0, 0xed86e61d0, 0x0}, {0xc001f95c50, 0xb}, 0xc0006c6100, {0x5719e90, 0x0, 0x0}, ...})
	/root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj-1/proxy/app_conn.go:85 +0x137
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2ec6cd5, 0x6}}, {0xc001f95c50, 0xb}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj-1/consensus/replay.go:319 +0xd78
github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc0005fbcd0, {0x3c93e10, 0xc0005bbb20})
	/root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj-1/consensus/replay.go:268 +0x3ca
github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2ec6cd5, 0x6}}, {0xc001f95c50, 0xb}, 0x1, 0x0, ...}, ...)
	/root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj-1/node/node.go:328 +0x198
github.com/cometbft/cometbft/node.NewNode(0xc000f4b760, {0x3c5f5f0, 0xc000f763c0}, 0xc000f51180, {0x3c44f00, 0xc000469608}, 0x3ca5c50?, 0x2a2b320?, 0xc000f512e0, {0x3c75840, ...}, ...)
	/root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj-1/node/node.go:778 +0x56d
main.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3c92520, 0xc001084540}, 0x0, {0x0, 0x0}, {0x3c9cc80, ...}, ...}, ...)
	/root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/start.go:220 +0x693
main.StartCmd.func2(0xc0008d8300?, {0x5719e90?, 0x0?, 0x0?})
	/root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/start.go:122 +0xe8
github.com/spf13/cobra.(*Command).execute(0xc0008d8300, {0x5719e90, 0x0, 0x0})
	/root/.go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc001201b00)
	/root/.go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/.go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/.go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.Execute(0xc0000061a0?)
	/root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/root.go:124 +0x1df
main.main()
	/root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/main.go:9 +0x1e

```

**Comment by imaiops** [comment]
I also encountered the same problem.

**Comment by mehrdadpfg** [comment]
same issue on testnet after restoring snapshot
re downloaded the genesis file as well

**Comment by mehrdadpfg** [comment]
same here on testnet after restoring a snapshot
we have had this node up and runnig for quite a long time

```panic: minimum commission rate cannot be nil: <nil>
Mar 15 11:22:18 injective-node-1 bash[1987203]: goroutine 1 [running]:
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.InitGenesis({{0x3ea2040, 0xc001c8fdc0}, {0x3ee6bf0, 0xc001634980}, {0x3ed1ac0, 0xc00054e280}, {0x7fcb326c13b0, 0xc001c8a410}, {0x3ee7910, 0xc0019b23d8}, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.3-inj-9/x/staking/keeper/genesis.go:31 +0x1c48
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{_, _}}, _, {_, _}, {_, _}, {_, _}}, {{0x3ecae50, ...}, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.3-inj-9/x/staking/module.go:172 +0x145
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x3ecae50, 0xc000130000}, {0x3ee77c0, 0xc000f838c0}, {{0x0, 0x0}, {0xc00109e110, 0xd}, 0x26aa60, ...}, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.3-inj-9/types/module/module.go:357 +0x433
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/InjectiveLabs/injective-core/injective-chain/app.(*InjectiveApp).InitChainer(_, {{0x3ecae50, 0xc000130000}, {0x3ee77c0, 0xc000f838c0}, {{0x0, 0x0}, {0xc00109e110, 0xd}, 0x26aa60, ...}, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/injective-chain/app/app.go:1081 +0x1af
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000dd4a00, {{0x2be0f8a0, 0xeda509583, 0x0}, {0xc00109e110, 0xd}, 0xc001c903a0, {0xc0003681e0, 0x3, 0x3}, ...})
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cosmos-sdk@v0.47.3-inj-9/baseapp/abci.go:78 +0x515
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0xc0013c0900, {{0x2be0f8a0, 0xeda509583, 0x0}, {0xc00109e110, 0xd}, 0xc001c903a0, {0xc0003681e0, 0x3, 0x3}, ...})
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj/abci/client/local_client.go:275 +0x118
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0xc000127008, {{0x2be0f8a0, 0xeda509583, 0x0}, {0xc00109e110, 0xd}, 0xc001c903a0, {0xc0003681e0, 0x3, 0x3}, ...})
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj/proxy/app_conn.go:85 +0x137
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x30d825a, 0x6}}, {0xc00109e110, 0xd}, 0x26aa60, 0x0, {{0x0, ...}, ...}, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj/consensus/replay.go:319 +0xd78
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc000fb1c88, {0x3eeac30, 0xc000cab0a0})
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj/consensus/replay.go:268 +0x3ca
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x30d825a, 0x6}}, {0xc00109e110, 0xd}, 0x26aa60, 0x0, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj/node/node.go:328 +0x198
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/cometbft/cometbft/node.NewNode(0xc000cb51e0, {0x3eb33f0, 0xc001bc3040}, 0xc02e270590, {0x3e968c0, 0xc02e27c630}, 0x4?, 0x2a10669?, 0xc02e2706d0, {0x3ecb0b8, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/!injective!labs/cometbft@v0.37.2-inj/node/node.go:778 +0x56d
Mar 15 11:22:18 injective-node-1 bash[1987203]: main.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3ee9340, 0xc00085e810}, 0x0, {0xc0010e0960, 0xd}, {0x3ef3bc0, ...}, ...}, ...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/start.go:230 +0x6b3
Mar 15 11:22:18 injective-node-1 bash[1987203]: main.StartCmd.func2(0xc001a52c00?, {0xc0019b4190?, 0x0?, 0x5?})
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/start.go:128 +0xe8
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/spf13/cobra.(*Command).execute(0xc001a52c00, {0xc0019b4140, 0x5, 0x5})
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/spf13/cobra.(*Command).ExecuteC(0xc00199c900)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
Mar 15 11:22:18 injective-node-1 bash[1987203]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
Mar 15 11:22:18 injective-node-1 bash[1987203]: main.Execute(0xc0000061a0?)
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/root.go:125 +0x1df
Mar 15 11:22:18 injective-node-1 bash[1987203]: main.main()
Mar 15 11:22:18 injective-node-1 bash[1987203]:         /root/actions-runner/_work/injective-core/injective-core/injective-core/cmd/injectived/main.go:9 +0x1e```
